from zeep import Client
# Unfortunately AWS python 3.6 doesn't support sqlite3
# from zeep.cache import SqliteCache
from zeep.transports import Transport

from netsuite import ns_config

# cache WSDL and XSD for a year
# cache = SqliteCache(timeout=60*60*24*365)
# transport = Transport(cache=cache)
transport = Transport()
client = Client(ns_config.WSDL_URL, transport=transport)

model = client.get_type

TokenPassport = model('ns0:TokenPassport')
TokenPassportSignature = model('ns0:TokenPassportSignature')
Passport = model('ns0:Passport')
RecordRef = model('ns0:RecordRef')
ListOrRecordRef = model('ns0:ListOrRecordRef')
StringCustomFieldRef = model('ns0:StringCustomFieldRef')
SelectCustomFieldRef = model('ns0:SelectCustomFieldRef')
BooleanCustomFieldRef = model('ns0:BooleanCustomFieldRef')
CustomFieldList = model('ns0:CustomFieldList')
ApplicationInfo = model('ns4:ApplicationInfo')
CustomerSearchBasic = model('ns5:CustomerSearchBasic')
AddressSearchBasic = model('ns5:AddressSearchBasic')
ItemSearchBasic = model('ns5:ItemSearchBasic')
TransactionSearchBasic = model('ns5:TransactionSearchBasic')
TransactionSearchAdvanced = model('ns19:TransactionSearchAdvanced')
SearchPreferences = model('ns4:SearchPreferences')
SearchBooleanField = model('ns0:SearchBooleanField')
SearchStringField = model('ns0:SearchStringField')
SearchLongField = model('ns0:SearchLongField')
SearchStringFieldOperator = model('ns1:SearchStringFieldOperator')
SearchMultiSelectField = model('ns0:SearchMultiSelectField')
SearchEnumMultiSelectField = model('ns0:SearchEnumMultiSelectField')
Customer = model('ns13:Customer')
CustomerAddressbook = model('ns13:CustomerAddressbook')
CustomerAddressbookList = model('ns13:CustomerAddressbookList')
Address = model('ns5:Address')
Country = model('ns6:Country')
CashSale = model('ns19:CashSale')
CashSaleItem = model('ns19:CashSaleItem')
CashSaleItemList = model('ns19:CashSaleItemList')
CashRefund = model('ns23:CashRefund')
CashRefundItem = model('ns23:CashRefundItem')
CashRefundItemList = model('ns23:CashRefundItemList')
CreditMemo = model('ns23:CreditMemo')
CreditMemoItem = model('ns23:CreditMemoItem')
CreditMemoItemList = model('ns23:CreditMemoItemList')
ReturnAuthorization = model('ns23:ReturnAuthorization')
ReturnAuthorizationItem = model('ns23:ReturnAuthorizationItem')
ReturnAuthorizationItemList = model('ns23:ReturnAuthorizationItemList')
SalesOrder = model('ns19:SalesOrder')
SalesOrderItem = model('ns19:SalesOrderItem')
SalesOrderItemList = model('ns19:SalesOrderItemList')
Invoice = model('ns19:Invoice')
InvoiceItem = model('ns19:InvoiceItem')
InvoiceItemList = model('ns19:InvoiceItemList')
GiftCertRedemptionList = model('ns19:GiftCertRedemptionList')
GiftCertRedemption = model('ns19:GiftCertRedemption')
GiftCertificate = model('ns17:GiftCertificate')
GiftCertificateSearchBasic = model('ns5:GiftCertificateSearchBasic')
CustomerCurrency = model('ns13:CustomerCurrency')
CustomerCurrencyList = model('ns13:CustomerCurrencyList')
ItemFulfillment = model('ns19:ItemFulfillment')
ItemFulfillmentItem = model('ns19:ItemFulfillmentItem')
ItemFulfillmentItemList = model('ns19:ItemFulfillmentItemList')
ItemFulfillmentPackage = model('ns19:ItemFulfillmentPackage')
ItemFulfillmentPackageList = model('ns19:ItemFulfillmentPackageList')
InitializeRecord = model('ns0:InitializeRecord')
InitializeRef = model('ns0:InitializeRef')
SearchCustomFieldList = model('ns0:SearchCustomFieldList')
SearchStringCustomField = model('ns0:SearchStringCustomField')
ItemReceipt = model('ns21:ItemReceipt')
ItemReceiptItem = model('ns21:ItemReceiptItem')
ItemReceiptItemList = model('ns21:ItemReceiptItemList')
TransferOrder = model('ns29:TransferOrder')
InventoryAdjustment = model('ns29:InventoryAdjustment')
InventoryAdjustmentInventory = model('ns29:InventoryAdjustmentInventory')
InventoryAdjustmentInventoryList = model('ns29:InventoryAdjustmentInventoryList')
InventoryTransfer = model('ns29:InventoryTransfer')
ItemSearch = model('ns17:ItemSearch')
ItemSearchAdvanced = model('ns17:ItemSearchAdvanced')
